"""
Portfolio Health Check Agent — the fully-implemented specialist.

Responsibilities (MONITOR + PROTECT quadrant):
  - Fetch live prices for all holdings via yfinance
  - Compute cost basis, current value, return, concentration metrics
  - Compare to user's preferred benchmark (or a sensible default)
  - Produce a structured JSON report + stream a plain-language narrative

Design decisions
----------------
1. **yfinance for market data**
   The assignment explicitly lists yfinance as an option and prohibits
   hardcoding market data. yfinance covers all tickers in the fixtures
   (NASDAQ, NYSE, EURONEXT, LSE, TSE) with exchange-suffix routing.

2. **Multi-currency normalization**
   Positions can be in USD, EUR, GBP, or JPY. We fetch live FX rates from
   yfinance (e.g., EURUSD=X, GBPUSD=X, JPYUSD=X) and convert everything to
   the user's base_currency before computing portfolio-level metrics.

3. **Benchmark comparison**
   We honour user.preferences.preferred_benchmark. If the ticker doesn't
   resolve, we fall back to a sensible default per country:
     US  → SPY (proxy for S&P 500)
     UK  → ISF.L (iShares FTSE 100)
     SG  → IWDA.L (MSCI World)
     JP  → 1306.T (Nikkei ETF)

4. **Empty portfolio**
   For user_004_empty (zero positions), we skip all financial calculations
   and return a BUILD-oriented response with onboarding guidance.

5. **Streaming**
   The narrative text is generated by a separate LLM call and streamed
   token-by-token back to the pipeline. The structured JSON report is
   emitted first as a 'metadata' SSE event.

6. **Regulatory disclaimer**
   Included in every response, as required.
"""
from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timezone
from typing import AsyncIterator, Optional

import yfinance as yf

from src.config import OPENAI_API_KEY, OPENAI_MODEL
from src.schemas import ClassifierResult, UserProfile

logger = logging.getLogger(__name__)

_DISCLAIMER = (
    "This report is generated by an AI system and is for informational "
    "purposes only. It does not constitute investment advice, a recommendation "
    "to buy or sell any security, or a solicitation of any investment. Past "
    "performance is not indicative of future results. Always consult a "
    "qualified financial adviser before making investment decisions."
)

# ---------------------------------------------------------------------------
# FX ticker map: currency → yfinance ticker for USD conversion rate
# ---------------------------------------------------------------------------
_FX_TICKERS = {
    "EUR": "EURUSD=X",
    "GBP": "GBPUSD=X",
    "JPY": "JPYUSD=X",
    "SGD": "SGDUSD=X",
    "USD": None,  # base
}

# Default benchmark per country
_COUNTRY_BENCHMARK = {
    "US": "SPY",
    "GB": "ISF.L",
    "SG": "IWDA.L",
    "JP": "1306.T",
}

_BENCHMARK_LABEL = {
    "SPY": "S&P 500 (SPY)",
    "QQQ": "NASDAQ-100 (QQQ)",
    "ISF.L": "FTSE 100 (ISF.L)",
    "IWDA.L": "MSCI World (IWDA.L)",
    "1306.T": "Nikkei 225 ETF (1306.T)",
    "S&P 500": "S&P 500 (SPY)",
    "MSCI World": "MSCI World (IWDA.L)",
    "FTSE 100": "FTSE 100 (ISF.L)",
    "NIKKEI 225": "Nikkei 225 ETF (1306.T)",
}

_BENCHMARK_TICKER_MAP = {
    "S&P 500": "SPY",
    "MSCI World": "IWDA.L",
    "FTSE 100": "ISF.L",
    "NIKKEI 225": "1306.T",
}


def _resolve_benchmark_ticker(user: UserProfile) -> tuple[str, str]:
    """Return (ticker, label) for the user's benchmark."""
    pref = (user.preferences.preferred_benchmark or "").strip()
    # Check canonical name aliases first (e.g. "S&P 500" → "SPY")
    if pref in _BENCHMARK_TICKER_MAP:
        ticker = _BENCHMARK_TICKER_MAP[pref]
        return ticker, _BENCHMARK_LABEL.get(pref, pref)
    # If the preference is already a raw ticker or known label (e.g. "QQQ", "SPY")
    if pref:
        return pref, _BENCHMARK_LABEL.get(pref, pref)
    # Fall back to country default
    country = user.country.upper()
    ticker = _COUNTRY_BENCHMARK.get(country, "SPY")
    return ticker, _BENCHMARK_LABEL.get(ticker, ticker)


def _fetch_price(ticker: str) -> Optional[float]:
    """Fetch the latest close price for *ticker*. Returns None on failure."""
    try:
        t = yf.Ticker(ticker)
        hist = t.history(period="5d")
        if hist.empty:
            return None
        return float(hist["Close"].iloc[-1])
    except Exception as exc:
        logger.warning("yfinance price fetch failed for %s: %s", ticker, exc)
        return None


def _fetch_period_return(ticker: str, start_date: str) -> Optional[float]:
    """
    Return the percentage return of *ticker* from *start_date* to today.
    start_date format: YYYY-MM-DD
    """
    try:
        t = yf.Ticker(ticker)
        hist = t.history(start=start_date)
        if len(hist) < 2:
            return None
        price_start = float(hist["Close"].iloc[0])
        price_end = float(hist["Close"].iloc[-1])
        if price_start == 0:
            return None
        return (price_end - price_start) / price_start * 100
    except Exception as exc:
        logger.warning("yfinance period return failed for %s: %s", ticker, exc)
        return None


def _fetch_fx_rate(currency: str, base: str = "USD") -> float:
    """Return 1 unit of *currency* in *base*. Returns 1.0 on failure."""
    if currency == base:
        return 1.0
    fx_ticker = _FX_TICKERS.get(currency)
    if fx_ticker is None:
        return 1.0
    price = _fetch_price(fx_ticker)
    return price if price else 1.0


def _compute_portfolio_metrics(
    user: UserProfile,
) -> dict:
    """
    Compute all portfolio metrics synchronously (called from async wrapper).

    Returns a dict with the full structured report.
    """
    positions = user.positions
    base_ccy = user.base_currency or "USD"

    if not positions:
        return {"empty": True}

    # --- Collect prices and FX rates ---
    all_tickers = list({p.ticker for p in positions})
    all_currencies = list({p.currency for p in positions})

    fx_rates: dict[str, float] = {
        ccy: _fetch_fx_rate(ccy, base_ccy) for ccy in all_currencies
    }

    prices: dict[str, Optional[float]] = {
        ticker: _fetch_price(ticker) for ticker in all_tickers
    }

    # --- Earliest purchase date (for benchmark comparison period) ---
    earliest_date = min(p.purchased_at for p in positions)

    # --- Position-level calculations ---
    position_data = []
    total_cost_base = 0.0
    total_value_base = 0.0

    for pos in positions:
        fx = fx_rates.get(pos.currency, 1.0)
        current_price = prices.get(pos.ticker)

        cost_base = pos.quantity * pos.avg_cost * fx
        if current_price is not None:
            value_base = pos.quantity * current_price * fx
        else:
            # Fall back to cost if no price available
            value_base = cost_base
            logger.warning("No price for %s — using cost basis", pos.ticker)

        pnl = value_base - cost_base
        pnl_pct = (pnl / cost_base * 100) if cost_base else 0.0

        total_cost_base += cost_base
        total_value_base += value_base

        position_data.append({
            "ticker": pos.ticker,
            "quantity": pos.quantity,
            "avg_cost": pos.avg_cost,
            "current_price": current_price,
            "currency": pos.currency,
            "value_base": value_base,
            "cost_base": cost_base,
            "pnl": pnl,
            "pnl_pct": round(pnl_pct, 2),
        })

    # Sort by value descending for concentration analysis
    position_data.sort(key=lambda x: x["value_base"], reverse=True)

    # --- Concentration risk ---
    top_1_pct = (
        position_data[0]["value_base"] / total_value_base * 100
        if total_value_base else 0
    )
    top_3_pct = (
        sum(p["value_base"] for p in position_data[:3]) / total_value_base * 100
        if total_value_base else 0
    )
    # Flag thresholds: >50% top-1 → high, >30% → medium, else low
    conc_flag = "high" if top_1_pct > 50 else ("medium" if top_1_pct > 30 else "low")

    # --- Overall performance ---
    total_pnl = total_value_base - total_cost_base
    total_return_pct = (total_pnl / total_cost_base * 100) if total_cost_base else 0.0

    # Annualized return (simple CAGR approximation)
    try:
        start_dt = datetime.strptime(earliest_date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        now_dt = datetime.now(timezone.utc)
        years_held = (now_dt - start_dt).days / 365.25
        if years_held > 0.05:  # at least ~18 days
            annualized_return_pct = (
                ((total_value_base / total_cost_base) ** (1 / years_held) - 1) * 100
                if total_cost_base else 0.0
            )
        else:
            annualized_return_pct = total_return_pct
    except Exception:
        annualized_return_pct = total_return_pct
        years_held = 0.0

    # --- Benchmark comparison ---
    bm_ticker, bm_label = _resolve_benchmark_ticker(user)
    benchmark_return_pct = _fetch_period_return(bm_ticker, earliest_date)
    if benchmark_return_pct is None:
        benchmark_return_pct = 0.0
        bm_label += " (unavailable)"
    alpha_pct = total_return_pct - benchmark_return_pct

    # --- Sector / asset-class analysis (from ticker prefixes / known ETFs) ---
    # Simple heuristic: flag bond ETFs (BND, TLT, AGG), broad ETFs (VTI, VOO, QQQ)
    bond_tickers = {"BND", "TLT", "AGG", "VGSH", "VGIT", "VGLT", "LQD", "HYG"}
    broad_etf = {"VTI", "VOO", "IWDA.L", "ISF.L", "SPY", "QQQ", "VXUS", "SCHD", "VYM"}
    has_bonds = any(p.ticker in bond_tickers for p in positions)
    has_broad_etf = any(p.ticker in broad_etf for p in positions)
    n_single_stocks = sum(
        1 for p in positions
        if p.ticker not in bond_tickers and p.ticker not in broad_etf
    )

    # --- Observations ---
    observations = []

    if conc_flag == "high":
        top_ticker = position_data[0]["ticker"]
        observations.append({
            "severity": "warning",
            "text": (
                f"{top_1_pct:.1f}% of your portfolio is in {top_ticker}. "
                "Concentration this high amplifies both gains and losses — "
                "a single bad quarter can significantly impact your wealth."
            ),
        })
    elif conc_flag == "medium":
        top_ticker = position_data[0]["ticker"]
        observations.append({
            "severity": "info",
            "text": (
                f"Your largest position ({top_ticker}) makes up {top_1_pct:.1f}% "
                "of your portfolio. Monitor this if it grows further."
            ),
        })

    if alpha_pct > 0:
        observations.append({
            "severity": "info",
            "text": (
                f"Your portfolio has outperformed {bm_label} by "
                f"{abs(alpha_pct):.1f}% since your earliest purchase."
            ),
        })
    elif alpha_pct < -5:
        observations.append({
            "severity": "warning",
            "text": (
                f"Your portfolio is underperforming {bm_label} by "
                f"{abs(alpha_pct):.1f}%. Consider whether your stock selection "
                "is adding value versus a simple index strategy."
            ),
        })

    if not has_bonds and user.age >= 50:
        observations.append({
            "severity": "warning",
            "text": (
                "You have no fixed-income exposure. At your age, most "
                "advisers recommend some bond allocation to reduce drawdown risk."
            ),
        })

    if not has_broad_etf and n_single_stocks >= 5:
        observations.append({
            "severity": "info",
            "text": (
                "You hold multiple single stocks without a broad-market ETF "
                "as a core. Adding a low-cost index fund (e.g., VTI or VXUS) "
                "can reduce idiosyncratic risk."
            ),
        })

    if user.risk_profile == "conservative" and conc_flag in ("high", "medium"):
        observations.append({
            "severity": "warning",
            "text": (
                "Your stated risk profile is conservative, but your portfolio "
                "concentration suggests higher risk than intended. "
                "Consider rebalancing toward diversified funds."
            ),
        })

    if total_return_pct < 0:
        observations.append({
            "severity": "warning",
            "text": (
                f"Your portfolio is currently down {abs(total_return_pct):.1f}% "
                "from cost. This is within normal market volatility, but review "
                "your thesis for each position."
            ),
        })

    # Position weight table (top 5 for the narrative)
    position_weights = [
        {
            "ticker": p["ticker"],
            "weight_pct": round(p["value_base"] / total_value_base * 100, 1),
            "pnl_pct": p["pnl_pct"],
            "value": round(p["value_base"], 2),
        }
        for p in position_data[:5]
    ]

    return {
        "empty": False,
        "total_value": round(total_value_base, 2),
        "total_cost": round(total_cost_base, 2),
        "base_currency": base_ccy,
        "concentration_risk": {
            "top_position_pct": round(top_1_pct, 1),
            "top_3_positions_pct": round(top_3_pct, 1),
            "flag": conc_flag,
        },
        "performance": {
            "total_return_pct": round(total_return_pct, 2),
            "annualized_return_pct": round(annualized_return_pct, 2),
            "total_pnl": round(total_pnl, 2),
            "years_measured": round(years_held, 1),
        },
        "benchmark_comparison": {
            "benchmark": bm_label,
            "portfolio_return_pct": round(total_return_pct, 2),
            "benchmark_return_pct": round(benchmark_return_pct, 2),
            "alpha_pct": round(alpha_pct, 2),
        },
        "top_positions": position_weights,
        "observations": observations,
        "disclaimer": _DISCLAIMER,
    }


async def _stream_narrative(
    report: dict,
    user: UserProfile,
    *,
    classifier_result: ClassifierResult,
) -> AsyncIterator[str]:
    """
    Stream a plain-language narrative for the health report.
    Uses OpenAI streaming so the first token arrives quickly.
    """
    from openai import AsyncOpenAI
    client = AsyncOpenAI(api_key=OPENAI_API_KEY)

    # Build a concise data summary for the prompt to save tokens
    top_pos = report.get("top_positions", [])
    perf = report.get("performance", {})
    conc = report.get("concentration_risk", {})
    bm = report.get("benchmark_comparison", {})
    obs = report.get("observations", [])

    obs_text = "\n".join(f"- [{o['severity'].upper()}] {o['text']}" for o in obs)
    top_pos_text = "\n".join(
        f"  {p['ticker']}: {p['weight_pct']}% of portfolio, P&L {p['pnl_pct']:+.1f}%"
        for p in top_pos
    )

    system = (
        "You are NestMind, an AI co-investor for novice investors. "
        "Write a clear, friendly portfolio health narrative in 3–4 short paragraphs. "
        "Use plain language — no jargon without explanation. "
        "Surface the 1–2 things that matter most. Be specific about the user's actual holdings. "
        "Do NOT repeat the disclaimer — it is added separately. "
        "Do NOT use bullet points — write in flowing prose."
    )

    user_msg = (
        f"User: {user.name}, age {user.age}, risk profile: {user.risk_profile}.\n"
        f"Portfolio value: {report['total_value']:,.0f} {report['base_currency']}\n"
        f"Total return: {perf.get('total_return_pct', 0):+.1f}%  "
        f"(annualised: {perf.get('annualized_return_pct', 0):+.1f}%)\n"
        f"Benchmark: {bm.get('benchmark', 'N/A')}, return: {bm.get('benchmark_return_pct', 0):+.1f}%  "
        f"Alpha: {bm.get('alpha_pct', 0):+.1f}%\n"
        f"Concentration — top position: {conc.get('top_position_pct', 0):.1f}%, "
        f"top 3: {conc.get('top_3_positions_pct', 0):.1f}%  [{conc.get('flag', '')} risk]\n"
        f"Top positions:\n{top_pos_text}\n"
        f"Key observations:\n{obs_text}\n\n"
        "Write the portfolio health narrative now."
    )

    try:
        stream = await client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user_msg},
            ],
            temperature=0.4,
            max_tokens=600,
            stream=True,
        )
        async for chunk in stream:
            delta = chunk.choices[0].delta.content
            if delta:
                yield delta
    except Exception as exc:
        logger.error("Narrative streaming failed: %s", exc)
        yield (
            f"\n\nYour portfolio is valued at {report['total_value']:,.0f} {report['base_currency']} "
            f"with a total return of {perf.get('total_return_pct', 0):+.1f}%. "
            f"Concentration flag: {conc.get('flag', 'unknown')}."
        )


async def _stream_empty_narrative(user: UserProfile) -> AsyncIterator[str]:
    """
    Stream a BUILD-oriented response for users with no positions.
    """
    from openai import AsyncOpenAI
    client = AsyncOpenAI(api_key=OPENAI_API_KEY)

    system = (
        "You are NestMind, an AI co-investor for novice investors. "
        "The user has completed KYC but has not yet made any investments. "
        "Write a warm, encouraging 3-paragraph response that: "
        "(1) acknowledges they're starting fresh, "
        "(2) explains the most important first step (e.g. understanding their goal and time horizon), "
        "(3) gives one concrete next action they can take on NestMind. "
        "Be specific, practical, and friendly. No jargon without explanation."
    )

    user_msg = (
        f"User: {user.name}, age {user.age}, "
        f"risk profile: {user.risk_profile}, country: {user.country}. "
        "They have no portfolio positions yet. Help them get started."
    )

    try:
        stream = await client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user_msg},
            ],
            temperature=0.5,
            max_tokens=400,
            stream=True,
        )
        async for chunk in stream:
            delta = chunk.choices[0].delta.content
            if delta:
                yield delta
    except Exception as exc:
        logger.error("Empty narrative streaming failed: %s", exc)
        yield (
            f"Welcome to NestMind, {user.name}! "
            "You have no positions yet — that's completely fine. "
            "Start by thinking about your financial goal and time horizon, "
            "then use our Product Recommendation feature to find a fund that fits."
        )


async def run(
    user: UserProfile,
    classifier_result: ClassifierResult,
) -> AsyncIterator[str]:
    """
    Main entry point for the Portfolio Health agent.

    Yields: SSE token strings (plain text narrative chunks).
    The structured report is returned first via the metadata channel
    (handled by pipeline.py).
    """
    # Compute metrics in a thread pool to avoid blocking the event loop
    loop = asyncio.get_event_loop()
    report = await loop.run_in_executor(
        None, _compute_portfolio_metrics, user
    )

    if report.get("empty"):
        # Store empty report in a well-known attribute for the pipeline
        run._last_report = {
            "empty": True,
            "observations": [
                {
                    "severity": "info",
                    "text": (
                        f"Welcome, {user.name}! Your account is verified and ready. "
                        "You have no positions yet — use NestMind to build your first allocation."
                    ),
                }
            ],
            "disclaimer": _DISCLAIMER,
        }
        async for token in _stream_empty_narrative(user):
            yield token
    else:
        run._last_report = report
        async for token in _stream_narrative(
            report, user, classifier_result=classifier_result
        ):
            yield token


# Attach report storage to the function object so pipeline.py can retrieve it
run._last_report: dict = {}
